spring:
  data:
    mongodb:
      uri: mongodb+srv://jeevanthitrya:o7Al2mKruxgi4yrR@cluster0.qapnxvx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 8080
  servlet:
    context-path: /journal
